name: Update YTLitePlus
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: latest
        run: |
          RES=$(curl -s "https://api.github.com/repos/YTLitePlus/YTLitePlus/releases/latest")
          echo "version=$(echo $RES | jq -r .tag_name)" >> $GITHUB_ENV
          echo "download_url=$(echo $RES | jq -r '.assets[0].browser_download_url')" >> $GITHUB_ENV

      - run: curl -L -o ./assets/YTLitePlus.ipa ${{ env.download_url }}

      - run: |
          RID=$(curl -s "https://api.github.com/repos/EscapeAltDelete/Updater/releases/tags/YTLitePlus" -H "Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}" | jq -r '.id')
          curl -X DELETE \
          -H 'Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}' \
          https://api.github.com/repos/EscapeAltDelete/Updater/releases/$RID

      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          tag_name: YTLitePlus
          release_name: YTLitePlus
          draft: false
          prerelease: false

      - id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./assets/YTLitePlus.ipa
          asset_name: YTLitePlus.ipa
          asset_content_type: application/octet-stream
