jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch latest release
        id: latest
        run: |
          LATEST=$(curl --silent "https://api.github.com/repos/YTLitePlus/YTLitePlus/releases/latest" | jq -r .tag_name)
          echo "version=$LATEST" >> $GITHUB_ENV

      - name: Download release asset
        run: |
          ASSET_URL=$(curl --silent "https://api.github.com/repos/YTLitePlus/YTLitePlus/releases/latest" | jq -r '.assets[0].browser_download_url')
          curl -L -o ./assets/YTlitePlus $ASSET_URL
