name: Update YTLitePlus
on: 
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - uses: houqp/download-release-assets@v1
        with:
          repo: YTLitePlus/YTLitePlus
          match: ".*YTLitePlus.*"
          token: ${{ secrets.MY_GITHUB_TOKEN }}
      - run: |
          FILE_NAME=$(ls | grep 'YTLitePlus.*')
          JSON=$(curl -sH "Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}" https://api.github.com/repos/EscapeAltDelete/Updater/releases/tags/YTLitePlus)
          RID=$(echo $JSON | jq -r '.id')
          curl -X DELETE -H 'Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}' https://api.github.com/repos/EscapeAltDelete/Updater/releases/$RID &
          DELETE_PID=$!
          wait $DELETE_PID
      - uses: ncipollo/release-action@main
        with:
          tag: YTLitePlus
          name: YTLitePlus
          body: "Latest release of YTLitePlus"
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          artifacts: ${{ env.FILE_NAME }}
